//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Archive
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int idUser { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string lastName { get; set; }
        public string firstName { get; set; }
        public string patronymic { get; set; }
        public int position { get; set; }
        public bool adopted { get; set; }
    
        public virtual PositionUsers PositionUsers { get; set; }
    }
}
