//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PP
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentPosition
    {
        public int id { get; set; }
        public int position { get; set; }
        public int typeDocument { get; set; }
    
        public virtual PositionUsers PositionUsers { get; set; }
        public virtual TypeDocument TypeDocument1 { get; set; }
    }
}
